# ---
# title: "Descriptive Analysis of Small-Mammal Community Data"
# ---

# This script performs the descriptive analysis and generates the primary figures
# and tables for the manuscript. It uses the processed data generated by the
# '01_load_data.R' script.
#
# INPUTS:
# - 'data/processed_data/descriptive_data.rds': An R object containing processed
#   detection histories and site data.
#
# OUTPUTS:
# - 'data/output/consolidated_rodent_trap.csv': A flattened CSV for data sharing.
# - 'output/figures/Figure_2_landuse_only.png': Heatmap of species detection rates.
# - 'output/figures/Supplementary_Figure_3a.png': Species accumulation by village.
# - 'output/figures/Supplementary_Figure_3b.png': Species accumulation by village and land use.
# - 'output/figures/Supplementary_Figure_5a.png': Seasonal detection rates by village.
# - 'output/figures/Supplementary_Figure_5b.png': Seasonal detection rates by land use.
# - 'output/tables/table_1a.rds': Data for Table 1 in the manuscript.

# 0. SETUP ------------------------------------------------------------------

source(here::here("R", "00_setup.R"))

# Load the processed data object created by the previous script.
observed_data <- read_rds(here("data", "processed_data", "descriptive_data.rds"))

# 1. DATA PREPARATION -----------------------------------------------------

# Unpack the main data frames from the loaded list for easier access.
# 'sites' contains one row for each trap deployment event.
sites <- observed_data$sites_grids$select_site %>%
  bind_rows() %>%
  select(date_set, site_id = unique_site, site, landuse, site_easting, site_northing, village, visit, grid_number, trap_id = trap_uid, trap_easting, trap_northing, elevation)

# 'detections' contains one row for each individual animal captured.
detections <- observed_data$detections %>%
  rename(trap_id = trap_uid) %>%
  left_join(sites %>%
              select(site_id, trap_id, date_set, landuse))

# Create a consolidated CSV file for data sharing purposes.
# This joins rodent capture data with detailed trap location and habitat info.
observed_data$detections %>%
  rename(trap_id = trap_uid) %>%
  left_join(sites) %>%
  ungroup() %>%
  write_csv(here("data", "output", "consolidated_rodent_trap.csv"))

# 2. CALCULATE TRAPPING EFFORT (TRAP NIGHTS) -----------------------------

# Calculate the total number of trap nights (TN) for each unique trap deployment.
tn_per_trap <- observed_data$non_processed_data$trap_data %>%
  tibble() %>%
  select(-geometry) %>%
  filter(village != "bambawo") %>%
  group_by(village, visit, grid_number, trap_number) %>%
  summarise(tn = n(), .groups = "drop") %>%
  mutate(trap_id = paste0(village, "_", visit, "_", grid_number, "_", trap_number)) %>%
  select(trap_id, tn)

# Summarize trap nights by different strata (village, land use, season) for later calculations.
tn_village_landuse <- sites %>%
  left_join(tn_per_trap, by = "trap_id") %>%
  group_by(village, landuse) %>%
  summarise(tn = sum(tn, na.rm = TRUE), .groups = "drop")

tn_village <- tn_village_landuse %>%
  group_by(village) %>%
  summarise(tn = sum(tn, na.rm = TRUE), .groups = "drop")

tn_landuse <- tn_village_landuse %>%
  group_by(landuse) %>%
  summarise(tn = sum(tn, na.rm = TRUE), .groups = "drop")

# Define seasons for seasonal analysis.
season_def <- tibble(month = 1:12, season = c(rep("Dry", 4), rep("Rainy", 6), rep("Dry", 2)))

tn_season <- sites %>%
  left_join(tn_per_trap, by = "trap_id") %>%
  mutate(month = month(date_set)) %>%
  left_join(season_def, by = "month") %>%
  group_by(village, season, landuse) %>%
  summarise(tn = sum(tn, na.rm = TRUE), .groups = "drop")


# 3. GENERATE TABLE 1 (Community Metrics) ---------------------------------

# --- 3.1. Calculate Species Richness ---
# First, create a base data frame of all unique sites.
richness_base <- sites %>%
  tibble() %>%
  distinct(village, landuse, site_id)

# Join detections and convert to presence (1) / absence (0).
richness_presence <- richness_base %>%
  left_join(detections %>% select(site_id, clean_names), by = "site_id") %>%
  mutate(present = if_else(is.na(clean_names), 0, 1))

# Calculate richness for different groupings.
richness_village <- richness_presence %>% filter(present == 1) %>% distinct(village, clean_names) %>% group_by(village) %>% summarise(species_richness = n(), .groups = "drop")
richness_landuse <- richness_presence %>% filter(present == 1) %>% distinct(landuse, clean_names) %>% group_by(landuse) %>% summarise(species_richness = n(), .groups = "drop")
richness_landuse_village <- richness_presence %>% filter(present == 1) %>% distinct(village, landuse, clean_names) %>% group_by(village, landuse) %>% summarise(species_richness = n(), .groups = "drop")

# --- 3.2. Calculate Shannon Diversity ---
diversity_base <- detections %>%
  group_by(village, landuse, clean_names) %>%
  summarise(n = n(), .groups = "drop") %>%
  filter(!is.na(clean_names))

diversity_village <- diversity_base %>% group_by(village) %>% summarise(N = sum(n), shannon_diversity = diversity(n, index = "shannon"), .groups = "drop")
diversity_landuse <- diversity_base %>% group_by(landuse) %>% summarise(N = sum(n), shannon_diversity = diversity(n, index = "shannon"), .groups = "drop")
diversity_landuse_village <- diversity_base %>% group_by(village, landuse) %>% summarise(N = sum(n), shannon_diversity = diversity(n, index = "shannon"), .groups = "drop")

# --- 3.3. Combine Metrics for Table 1 ---

# A. Summaries by village and land use
village_landuse_summary <- diversity_landuse_village %>%
  left_join(richness_landuse_village, by = c("village", "landuse")) %>%
  left_join(tn_village_landuse, by = c("village", "landuse"))

# B. Summaries for village totals
village_total_summary <- diversity_village %>%
  left_join(richness_village, by = "village") %>%
  left_join(tn_village, by = "village") %>%
  mutate(landuse = "total") # Use lowercase for consistency

# C. Summaries for "All villages" by land use
all_villages_landuse_summary <- diversity_base %>%
  group_by(landuse) %>%
  summarise(N = sum(n), shannon_diversity = diversity(n, index = "shannon"), .groups = "drop") %>%
  left_join(richness_landuse, by = "landuse") %>%
  left_join(tn_village_landuse %>% group_by(landuse) %>% summarise(tn = sum(tn)), by = "landuse") %>%
  mutate(village = "All villages")

# D. Grand total for "All villages"
all_villages_total_summary <- diversity_base %>%
  summarise(N = sum(n), shannon_diversity = diversity(n, index = "shannon"), .groups = "drop") %>%
  mutate(
    species_richness = n_distinct(diversity_base$clean_names),
    tn = sum(tn_village$tn),
    village = "All villages",
    landuse = "total" # Use lowercase for consistency
  )

# Combine all summaries into the final table structure
table_1_data <- bind_rows(
  village_landuse_summary,
  village_total_summary,
  all_villages_landuse_summary,
  all_villages_total_summary
) %>%
  # Use forcats for robust factor manipulation
  mutate(
    # Recode village names to be capitalized for the table display
    village = fct_recode(village,
                         "Baiama" = "baiama",
                         "Lalehun" = "lalehun",
                         "Lambayama" = "lambayama",
                         "Seilama" = "seilama"),
    # Set the final order for the village factor to place the summary last
    village = fct_relevel(village, "Baiama", "Lalehun", "Lambayama", "Seilama", "All villages"),
    # Recode landuse names and set order
    landuse = factor(landuse,
                     levels = c("village", "agriculture", "forest", "total"),
                     labels = c("Village", "Agriculture", "Forest", "Total")),
    # Round diversity and create TN string
    shannon_diversity = round(shannon_diversity, 2),
    tn = replace_na(tn, 0), # Replace NA trap nights with 0 before pasting
    `TN (TS %)` = paste0(tn, " (", round(N / tn * 100, 1), "%)")
  ) %>%
  select(village, landuse, N, `TN (TS %)`, species_richness, shannon_diversity) %>%
  # Arrange the data to ensure rows are grouped correctly for flextable
  arrange(village, landuse)

write_rds(table_1_data, here("output", "tables", "table_1a.rds"))


# 4. GENERATE FIGURE 2 (Detection Rate Heatmap) ---------------------------
# Calculate total number of detections for each species across the entire study.
total_species_counts <- detections %>%
  ungroup() %>%
  filter(!is.na(clean_names)) %>%
  count(clean_names, name = "total_n")

# Calculate detection rate (per 1,000 TN) for each species by land use, aggregated across all villages.
fig_2_data <- detections %>%
  group_by(landuse, clean_names) %>%
  summarise(n_detected = n(), .groups = "drop") %>%
  filter(!is.na(clean_names)) %>%
  # Join total trap nights for each land use
  left_join(tn_village_landuse %>% group_by(landuse) %>% summarise(tn = sum(tn)), by = "landuse") %>%
  # Join total species counts for labeling
  left_join(total_species_counts, by = "clean_names") %>%
  # Use rowwise to create the axis labels correctly
  rowwise() %>%
  mutate(
    detection_rate = n_detected / tn,
    # Create a clean species name factor ordered by the predefined vector
    species_name = factor(str_to_sentence(str_replace_all(clean_names, "_", " ")), levels = species_order_plots),
    # Create the full axis label by pasting the species name and total count
    axis_label = paste0(species_name, " (N = ", total_n, ")"),
    # Create the label for the tiles (count within that land use)
    n_label = paste0("n = ", n_detected)
  ) %>%
  ungroup() %>%
  # Convert the final axis label to a factor and order it based on the species_name factor
  mutate(
    axis_label = factor(axis_label, levels = unique(axis_label[order(species_name)])),
    landuse = factor(str_to_sentence(landuse), levels = c("Forest", "Agriculture", "Village"))
  )

# Create a vector to control the font face (bolding) of the y-axis labels.
# This checks if the level of the reversed factor contains "Mastomys natalensis".
y_axis_fontface <- if_else(
  str_detect(levels(fct_rev(fig_2_data$axis_label)), "Mastomys natalensis"),
  "bold.italic", "italic"
)

# Create the plot.
fig_2_landuse <- ggplot(data = fig_2_data, aes(x = landuse, y = fct_rev(axis_label), fill = detection_rate, label = n_label)) +
  geom_tile(color = "white", lwd = 0.5) +
  geom_label(fill = "white") +
  # Updated scale for trap success percentage
  scale_fill_viridis_c(
    trans = scales::log10_trans(),
    name = "Trap Success (%)",
    breaks = c(0.0001, 0.0005, 0.001, 0.005),
    # scales::percent_format to automatically create percentage labels
    labels = scales::percent_format(accuracy = 0.01)
  ) +
  labs(y = element_blank(), x = "Land Use") +
  theme_bw() +
  theme(
    legend.position = "bottom",
    legend.key.width = unit(1.5, "cm"),
    axis.text = element_text(size = 12),
    axis.text.y = element_text(face = y_axis_fontface)
  )

# Save the plot.
save_plot(plot = fig_2_landuse, filename = here("output", "figures", "Figure_2_landuse_only.png"), base_width = 8, base_height = 7)

# 5. GENERATE SUPP. FIGURE 3 (Species Accumulation Curves) ----------------
# First, get a list of unique detections (one row per species per site).
unique_detections <- detections %>%
  ungroup() %>%
  filter(!is.na(clean_names)) %>%
  distinct(site_id, clean_names) %>%
  mutate(present = 1)

# Now, create the site x species matrix.
spec_accum_data <- sites %>%
  # Start with the full list of all 2,068 unique sites.
  distinct(site_id, village, landuse) %>%
  # Join the presence data. Sites with no detections will have NA for clean_names and present.
  left_join(unique_detections, by = "site_id") %>%
  # Pivot to the wide site-by-species format.
  pivot_wider(id_cols = c(site_id, village, landuse),
              names_from = clean_names,
              values_from = present,
              values_fill = 0) %>%
  # The pivot creates a column named `NA` for sites that had no detections. This must be removed.
  select(-`NA`)

# --- 5.1. Accumulation by Village ---
# Programmatically generate accumulation curves for each village.
village_accumulation <- spec_accum_data %>%
  group_by(village) %>%
  nest() %>%
  mutate(
    specaccum_obj = map(data, ~ specaccum(select(., -site_id, -landuse), method = "exact")),
    results = map(specaccum_obj, ~ tibble(Sites = .x$sites, Richness = .x$richness, SD = .x$sd))
  ) %>%
  select(village, results) %>%
  unnest(cols = results) %>%
  mutate(village = str_to_sentence(village))

# --- 5.2. Accumulation by Village and Land Use ---
# Programmatically generate curves for each village/land use combination.
village_landuse_accumulation <- spec_accum_data %>%
  group_by(village, landuse) %>%
  nest() %>%
  mutate(
    specaccum_obj = map(data, ~ specaccum(select(., -site_id), method = "exact")),
    results = map(specaccum_obj, ~ tibble(Sites = .x$sites, Richness = .x$richness, SD = .x$sd))
  ) %>%
  select(village, landuse, results) %>%
  unnest(cols = results) %>%
  mutate(village = str_to_sentence(village))

# --- 5.3. Create and Save Plots ---
# Plot A: By Village
plot_accum_village <- ggplot(village_accumulation,
                             aes(x = Sites, y = Richness, colour = village, fill = village)) +
  geom_line() +
  geom_ribbon(aes(ymin = Richness - SD, ymax = Richness + SD), alpha = 0.2, linetype = 1) +
  scale_colour_manual(values = village_palette, name = "Village") +
  scale_fill_manual(values = village_palette, name = "Village") +
  labs(title = "A) Species Accumulation by Village", x = "Sampling Effort (Grid Cells)", y = "Species Richness") +
  theme_bw()

# Plot B: By Village and Land Use
plot_accum_landuse <- ggplot(village_landuse_accumulation, aes(x = Sites, y = Richness, color = village, fill = village)) +
  geom_line() +
  geom_ribbon(aes(ymin = Richness - SD, ymax = Richness + SD), alpha = 0.2, linetype = 1) +
  facet_wrap(~ factor(landuse, levels = c("forest", "agriculture", "village"), labels = c("Forest", "Agriculture", "Village"))) +
  scale_colour_manual(values = village_palette, name = "Village") +
  scale_fill_manual(values = village_palette, name = "Village") +
  labs(title = "B) Species Accumulation by Village and Land Use", x = "Sampling Effort (Grid Cells)", y = "Species Richness") +
  theme_bw() +
  theme(legend.position = "bottom")

# Save plots
save_plot(plot = plot_accum_village, base_width = 8, base_height = 6, filename = here("output", "figures", "Supplementary_Figure_3a.png"))
save_plot(plot = plot_accum_landuse, base_width = 10, base_height = 8, filename = here("output", "figures", "Supplementary_Figure_3b.png"))


# 6. GENERATE SUPP. FIGURE 5 (Seasonal Detections) ------------------------

# --- 6.1. Trap Success by Season ---
season_trap_success_data <- detections %>%
  mutate(month = month(date_set)) %>%
  left_join(season_def, by = "month") %>%
  group_by(clean_names, village, season) %>%
  summarise(n_detected = n(), .groups = "drop") %>%
  left_join(tn_season %>% group_by(village, season) %>% summarise(tn = sum(tn)), by = c("village", "season")) %>%
  # Calculate trap success as a percentage
  mutate(trap_success = (n_detected / tn) * 100)

plot_season_detection <- ggplot(season_trap_success_data, aes(x = season, y = trap_success, fill = season)) +
  geom_boxplot() +
  facet_wrap(~ factor(str_to_sentence(str_replace_all(clean_names, "_", " ")), levels = species_order_plots), scales = "free_y") +
  # Ensure the y-axis for each facet starts at 0
  scale_y_continuous(limits = c(0, NA)) +
  labs(
    fill = element_blank(),
    y = "Trap Success (%)", # Updated label
    x = "Season",
    title = "A) Village-level species trap success by season"
  ) +
  theme_bw()

# --- 6.2. Trap Success by Season and Land Use ---
season_landuse_data <- detections %>%
  mutate(month = month(date_set)) %>%
  left_join(season_def, by = "month") %>%
  group_by(clean_names, village, season, landuse) %>%
  summarise(n_detected = n(), .groups = "drop") %>%
  left_join(tn_season, by = c("village", "season", "landuse")) %>%
  # Calculate trap success as a percentage
  mutate(
    trap_success = (n_detected / tn) * 100,
    landuse = factor(landuse, labels = c("Forest", "Agriculture", "Village"))
  )

plot_season_landuse <- ggplot(season_landuse_data, aes(x = season, y = trap_success, fill = landuse)) +
  geom_boxplot(position = position_dodge(preserve = "single")) +
  facet_wrap(~ factor(str_to_sentence(str_replace_all(clean_names, "_", " ")), levels = species_order_plots), scales = "free_y") +
  # Ensure the y-axis for each facet starts at 0
  scale_y_continuous(limits = c(0, NA)) +
  scale_fill_manual(values = landuse_palette, name = "Land Use") +
  labs(
    y = "Trap Success (%)", # Updated label
    x = "Season",
    title = "B) Land use-level species trap success by season"
  ) +
  theme_bw()

# Save plots
save_plot(plot = plot_season_detection, filename = here("output", "figures", "Supplementary_Figure_5a.png"), base_width = 12, base_height = 8)
save_plot(plot = plot_season_landuse, filename = here("output", "figures", "Supplementary_Figure_5b.png"), base_width = 12, base_height = 8)
